name: Node.js CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    nodejs:
        uses: zakodium/workflows/.github/workflows/nodejs.yml@nodejs-v1
        with:
            node-version-matrix: '[22,24]'
            lint-check-types: true
            upload-coverage: false
            # Not a package
            disable-test-package: true
